{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airflow-helm.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: airflow-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airflow-helm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-postgres
  template:
    metadata:
      labels:
        app: airflow-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password }}
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
{{- end }}
